### ISSUE TITLE
Ability to disable templating

### ISSUE THREAD

**Issue by danaki** [yokai-php/messenger-bundle#36]
I'm trying to code a channel for Mandrill. The difference is that templates created via their site's from a web-interface. Mandrill's REST API allows us to call a send method providing template name and template vars for substitution. So I see following problems:
 * "template" option is required, but ok, I can make a dummy one and use "template_name" under channel options configuration.
 * more major problem is that I have to create a dummy twig template just to make ContentBuilder do not raise an exception in getBody() complaining about missing template which I don't actually need because mail body is rendered on Mandrill's side.

My config currently looks like:
```
yokai_messenger:
    messages:
        -
            id:       verify_email
            channels: [mandrill]
            defaults:
                template: dummy.twig
                template_vars: ['reg_link', 'username', 'password']
            options:
                mandrill:
                    template_name: mail.registration_new
```
